version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: magento
       MYSQL_USER: magento
       MYSQL_PASSWORD: magento
    
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
      - "8580:80"
     links:
      - db

   magento:
     depends_on:
       - db
     image: alexcheng/magento2:latest
     volumes:
      - magento_root:/var/www/html/
      - php_config:/usr/local/etc/php
     ports:
       - "8002:80"
     restart: always
     environment:
       MAGENTO_DB_HOST: db:3306
       MAGENTO_DB_USER: magento
       MAGENTO_DB_PASSWORD: magento
       MAGENTO_DB_NAME: magento

volumes:
   db_data: {}
   magento_root: {}
   php_config: {}
  